# Generated by Django 4.0.1 on 2022-01-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosage',
            name='dose_timing',
            field=models.CharField(choices=[('Per Day', '1/d'), ('Per Half Day', '1/h'), ('Per Quarter Hour', '1/Q')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='dob',
            field=models.DateField(),
        ),
    ]
