# Generated by Django 4.0.1 on 2022-01-13 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_dosage_dose_timing_alter_patientdetails_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='doctor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='backend.doctordetails'),
        ),
    ]
